#!/bin/bash

# Fast boredbutton installer
# Use for updater only, unless system does not support building
# Does not set up PATH.

rm ~/bin/bored
cp bored ~/bin/
chmod ~/bin/bored 777

rm ~/.bored/defaultlist.txt
cp defaultlist.txt ~/.bored/
rm ~/.bored/defaultnoid.txt
cp defaultnoid.txt ~/.bored/


